Junit test for Payment and PaymentList
MarisGarrett19/CSYM026-Test pull request #5
Opened 2021-03-20 11:25 UTC by proj-jeni

Signed-off-by: proj-jeni <lourdujenifa@gmail.com>

2021-03-20 11:34 UTC, MarisGarrett19 commented
Hi @proj-jeni the tests are a good start. You could improve on them by doing some additional tests around the code. For example when calling `.getPayment()` you haven't tested what happens if there are no items in the list when you try to find one. 

Another thing you could do is use the `setUp()` and `tearDown()` methods to reduce how much code you have to write in your tests. You could look at the `TenantListTests` file in the main branch for an example.

2021-03-22 10:20 UTC, MarisGarrett19 requested changes

2021-03-22 10:20 UTC, MarisGarrett19 commented on Hostel Case Study/Tests/PaymentListTest.java
> +	public void positiontest() {
The names of these could be improved by making them describe what the test does rather than just name the method. For example, this one could be named `getPaymentShouldReturnPaymentAtPosition`. From that you can tell that this test is testing that the `getPayment` method returns the payment at the given position and if you have to add more tests for this method later you can do it more easily (You can look at the examples I added to see what kind of names make it easier). If the name is descriptive it makes it easier for other members of the group to understand the code.

2021-03-22 10:20 UTC, MarisGarrett19 commented on Hostel Case Study/Tests/getMonth.java
> +
You should name the class something like `PaymentTests` instead of `getMonth` it makes it clearer what it does.

2021-03-22 23:30 UTC, proj-jeni commented on Hostel Case Study/Tests/getMonth.java
> +
I have added the changes. Thanks

2021-03-22 23:31 UTC, proj-jeni commented on Hostel Case Study/Tests/PaymentListTest.java
> +	public void positiontest() {
I have changed the names.

2021-03-23 10:25 UTC, MarisGarrett19 commented
Those tests are much better. You don't need to put the word test at the start of each one. The whole class is called `PaymentTest` so everything in the class is a test.

One other thing is that the code could be made cleaner for example, you have a lot of blank lines all over the place, inconsistent naming and lots of the lines are indented in different ways. I know it sounds stupid but when code isn't formatted consistently it's much harder to read and understand and since we are all going to have to look at and understand each others code I think it's important we try and keep it clean. For example, if `testgetPaymentfromPosition` was named `getPaymentFromPosition` the capital letters make it far easier to read the name and understand what the code does.

But good work, there is nothing incorrect with the code itself just a few pointers to help make the group project easier. Do you want to fix the formatting a bit so you can get used to it all?

2021-03-23 11:22 UTC, MarisGarrett19 approved these changes

2021-03-23 11:22 UTC, merged